### ISSUE TITLE
Dialog confirm not showing buttons

### ISSUE THREAD

**Issue by javierrdzm** [lusaxweb/vuesax#520]
Dialog type confirm is not showing the buttons

OS: Windows 10
Node: 8.11.3
Vuesax: 3.8.39
Browser: Chrome 73.0.3683.86

![image](https://user-images.githubusercontent.com/15720946/55038156-8ccf1f00-4fe5-11e9-8388-d55e3e4b4182.png)

**Comment by jsinhSolanki** [comment]
This fixed in latest version. Please update vuesax. Current version 3.8.49

**Comment by Gyuyeol** [comment]
same problem in 3.8.49

**Comment by jsinhSolanki** [comment]
Create code sandbox so members can test.
Thanks

**Comment by javierrdzm** [comment]
I just updated to 3.8.49 and i still having the same error.
But i tried on JSFiddle and it works, i don't know what's wrong.
[JSFiddle](https://jsfiddle.net/5ehbtqjz/)
![image](https://user-images.githubusercontent.com/15720946/55098581-a757d580-5083-11e9-847d-a17027a7eef5.png)
![image](https://user-images.githubusercontent.com/15720946/55098616-b5a5f180-5083-11e9-81e5-fa435873545e.png)

**Comment by Gyuyeol** [comment]
I installed vuesax from master branch and it works.

weird.

![sc git](https://user-images.githubusercontent.com/6046972/55144439-31876300-5184-11e9-9578-1b0cecf0488e.png)

**Comment by javierrdzm** [comment]
Still not working for me on 3.8.52

**Comment by AndyChuang1** [comment]
Still not working for me on 3.8.59

**Comment by ziltonvasconcelos** [comment]
same for me on 3.8.59

**Comment by devv66** [comment]
Still not working. 3.8.64

**Comment by Pedrazl** [comment]
It´s working fine for me on 3.8.61. Please, provide a codepen to check the problem.

**Comment by JhonatanPereira** [comment]
Still not working. Tested in 3.8.61, 62 and 64

**Comment by tiagosimoesdev** [comment]
I'm using 3.10.4 and it works
