### ISSUE TITLE
Vuesax in Electron (Mac & Windows)

### ISSUE THREAD

**Issue by RALMAZ** [lusaxweb/vuesax#76]
I test Vuesax in Electron-Vue
1. Need fix select in Windows (I have win 7, yarn, last public vuesax, electron 2 and last electron-vue)
    Dont select - only show variants
    I try to find resolution for this bug, and i send PR, if complete fix

2. Button in MacOS 10.12 Sierra
Vuesax button dont be a visibile on this platform
Maybe need some polifile or something else, pardon I do not have a permanent MacOS for the test

And something good:
 Vuesax Chips in Electron - 10/10, Best
 In all platform, i love it

**Comment by RALMAZ** [comment]
Ok, tomorrow I will publish a repository with problems

**Comment by luisDanielRoviraContreras** [comment]
thank you very much

**Comment by RALMAZ** [comment]
Wow I have hard annomaly in last ver Chrome (Windows, not Electron)
![2018-05-18_23-38-21](https://user-images.githubusercontent.com/26162860/40256929-ecf8f7ca-5af4-11e8-8148-859576325a7d.gif)

**Comment by luisDanielRoviraContreras** [comment]
Ready and the problem is solved was something of css thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
You could pass me capture of the problems in electron thank you very much

**Comment by RALMAZ** [comment]
I publish repo here 
https://github.com/RALMAZ/Electron-Vuesax
`yarn`
`yarn run dev`

A bug with Windows select does not play, so it was a problem with my code :+1: 

A bug with buttons on macOs still exists :crying_cat_face:

**Comment by luisDanielRoviraContreras** [comment]
Please, if the problem keeps happening, let me know and show me with images thank you very much
